### ISSUE TITLE
SysTickの初期設定に関して

### ISSUE THREAD

**Issue by Embeded-ojisan** [garasubo/bookos#1]
始めまして、
Rustで始める自作組み込みOS入門の読者です。

掲題の件に関してですが、
SysTickの初期設定(systick::init())でCALIBの値を100倍してRVRで書き込んでますが、
私のWio-terminalだとRVRのTENMSの部分が0のため、
SysTickが起動しません。
一方、試しにRVRに対して直値で書き込んでみたところ起動しました。

この現象について心当たりあればお教えいただければと思います。

**Comment by garasubo** [comment]
SystickのCALIBレジスタのTENMSフィールドはオプショナルで、利用できないプロセッサもあるようです。私の手元のwio terminalだと動いたはずなのですが、ものによっては違うプロセッサが使われているのかもしれません。
その場合は、RVRに書き込む値はクロックの周波数から10ms分のカウントを計算して書き込むことになるかと思います

**Comment by garasubo** [comment]
こちらの件、私の勘違いでチェックが漏れていてTENMSフィールドは自分の手元でも0になってました。ですので、RVRに値を直に書き込むのが正解です。後に修正版を出す予定ですので、しばしお待ちいただけると幸いです

**Comment by Embeded-ojisan** [comment]
承知しました。
お忙しいところ対応いただきありがとうございます。

**Comment by garasubo** [comment]
こちらのレポジトリのソースコード及び技術書展のPDFの方更新しました。報告ありがとうございます。
